name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Stephanny9313
          outputs: |
            dist/snake.svg?color_snake=#23b0b4&color_dots=#fdf8f0

      - name: Copy Snake to Profile
        run: |
          mkdir -p ./output
          cp dist/snake.svg ./output/snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: output/snake.svg
